test::
	rm -rf
	python -m venv venv
	. venv/bin/activate && pip install -U pip
	. venv/bin/activate && pip install -U -i https://test.pypi.org/simple/ st-pagination-buttons
	#. venv/bin/activate && pip install -U  st-pagination-buttons
	. venv/bin/activate && streamlit run test_app.py
